defmodule AshPlatform.WalletActions.LaunchAbiTest do
  @moduledoc """
  The launch encoder, proved against Foundry rather than against itself.

  Every selector, topic and calldata vector here is compared with an independent
  `cast` derivation, because calldata generated by the same Elixir encoder it is
  meant to prove is not evidence of anything.
  """

  use ExUnit.Case, async: true

  alias AshPlatform.WalletActions.LaunchAbi

  @treasury "0x1111111111111111111111111111111111111111"

  @unit Integer.pow(10, 18)
  @uint128_max Integer.pow(2, 128) - 1
  @max_reachable_raise 658_201_822_928_399_999_999_999_581_824_872_526

  @base %{
    name: "Regent",
    symbol: "RGT",
    description: "A launch.",
    website: "https://regents.sh",
    image: "https://regents.sh/i.png",
    treasury: @treasury,
    required_regent_raised: 1_000 * @unit,
    expected_launch_fee: 1_000_000 * @unit
  }

  describe "SELECTORS_ARE_DERIVED_NOT_ASSERTED: every admitted signature is Foundry's own" do
    test "the one customer call keeps its exact literal tuple signature and selector" do
      assert LaunchAbi.signature(:launch) ==
               "launch((string,string,string,string,string,address,uint128,uint256))"

      assert LaunchAbi.selector(:launch) == "0xd0464e3e"
      assert cast(["sig", LaunchAbi.signature(:launch)]) == LaunchAbi.selector(:launch)
    end

    test "every read this lane prepares derives its selector from its declared signature" do
      for id <-
            [:launch_fee, :launches_paused, :strategy, :launches, :launch_id_of_subject] ++
              [:factory, :hook | LaunchAbi.terms()] do
        assert cast(["sig", LaunchAbi.signature(id)]) == LaunchAbi.selector(id),
               "#{LaunchAbi.signature(id)} selector disagrees with cast"
      end
    end

    test "every launch evidence topic is an independent Keccak-256 of its exact signature" do
      for id <- [:launch_created, :launch_fee_collected] do
        assert cast(["keccak", LaunchAbi.signature(id)]) == LaunchAbi.selector(id)
      end

      assert LaunchAbi.selector(:launch_created) ==
               "0x7b5b327fb976e7bf5fb279515b3ea1821166f52c0b46e5825f0146b249f963f2"

      assert LaunchAbi.selector(:launch_fee_collected) ==
               "0x9f3b0730114747603d4395bfe87ba93159db303d7898a3a197877eb01a64b9c6"
    end
  end

  describe "CALLDATA_MATCHES_FOUNDRY: the one dynamic tuple encodes exactly" do
    test "a representative launch matches cast byte for byte" do
      assert_matches_cast(@base)
    end

    test "a fractional REGENT raise is scaled to 18-decimal atomic units and encoded as one" do
      assert LaunchAbi.atomic_raise("1000.5") == {:ok, 1_000_500_000_000_000_000_000}

      assert_matches_cast(%{@base | required_regent_raised: 1_000_500_000_000_000_000_000})
    end

    test "the smallest representable raise survives the whole round trip" do
      assert LaunchAbi.atomic_raise("0.000000000000000001") == {:ok, 1}
      assert_matches_cast(%{@base | required_regent_raised: 1})
    end

    test "multibyte metadata rides as its exact UTF-8 bytes with the right offsets and padding" do
      assert_matches_cast(%{
        @base
        | name: "Ωμέγα 研究 🚀",
          symbol: "Ω",
          description: "é",
          website: "x",
          image: "y"
      })
    end

    # Thirty-two bytes exactly fills one word and thirty-three spills into a
    # second, which is where an off-by-one in the tail padding would show.
    test "metadata on either side of a word boundary keeps every later offset exact" do
      for length <- [31, 32, 33, 64, 65] do
        assert_matches_cast(%{@base | description: String.duplicate("a", length)})
      end
    end

    test "the strategy maximum and the uint128 ceiling both encode exactly" do
      assert_matches_cast(%{@base | required_regent_raised: @max_reachable_raise})
      assert_matches_cast(%{@base | required_regent_raised: @uint128_max})
    end

    test "a zero fee and a zero raise are ordinary words, not absent ones" do
      assert_matches_cast(%{@base | expected_launch_fee: 0, required_regent_raised: 0})
    end
  end

  describe "EXACT_STRING_ARITHMETIC: the raise is scaled without a decimal context" do
    # `Decimal`'s default 28-digit context cannot represent the 36-digit strategy
    # maximum, so the conversion is string arithmetic and is proved to be exact
    # at the exact boundary that context would round.
    @maximum_decimal "658201822928399999.999999581824872526"

    test "the 36-digit strategy maximum converts with no rounding at all" do
      assert LaunchAbi.atomic_raise(@maximum_decimal) == {:ok, @max_reachable_raise}

      # The pinned `Decimal` context carries 34 digits of precision and this
      # boundary needs 36, so that path cannot even read the maximum, let alone
      # prove a raise sits on it. That is why this lane does string arithmetic.
      assert Decimal.Context.get().precision == 34
      assert Decimal.parse(@maximum_decimal) == :error
    end

    test "a whole number pads to exactly eighteen zeros" do
      assert LaunchAbi.atomic_raise("1") == {:ok, @unit}

      assert LaunchAbi.atomic_raise("12345678901234567890") ==
               {:ok, 12_345_678_901_234_567_890 * @unit}
    end

    test "excess precision, a sign, an exponent and every other malformed input are refused" do
      for malformed <- [
            "1.0000000000000000001",
            "-1",
            "+1",
            "1e18",
            "1.",
            ".5",
            "1,000",
            " 1",
            "1 ",
            "abc",
            "",
            "0x1",
            "1.2.3"
          ] do
        assert LaunchAbi.atomic_raise(malformed) == :error, "#{inspect(malformed)} was accepted"
      end

      for zero <- ["0", "0.0", "0.000000000000000000"] do
        assert LaunchAbi.atomic_raise(zero) == :error
      end

      assert LaunchAbi.atomic_raise(nil) == :error
      assert LaunchAbi.atomic_raise(1) == :error
    end
  end

  describe "SIGNED_TERMS_DECODE_SIGNED: an unsigned word is not the value" do
    test "the exact positive tick spacing decodes to itself" do
      assert LaunchAbi.int24(60) == {:ok, 60}
      assert "60" |> word() |> LaunchAbi.int24() == {:ok, 60}
    end

    test "a sign-extended negative word is brought back rather than read as an enormous number" do
      assert "-60" |> word() |> LaunchAbi.int24() == {:ok, -60}
      assert LaunchAbi.int24(Integer.pow(2, 256) - 1) == {:ok, -1}
    end

    test "a word outside the int24 range is not a tick spacing at all" do
      assert LaunchAbi.int24(Integer.pow(2, 23)) == :error
      assert LaunchAbi.int24(Integer.pow(2, 256) - Integer.pow(2, 23) - 1) == :error
      assert LaunchAbi.int24(-1) == :error
    end
  end

  describe "RECORDED_LAUNCHES_DECODE_EXACTLY: an unknown id is absence, not a launch" do
    test "an all-zero record is absent and a whole one names its five addresses" do
      assert LaunchAbi.launch_record([0, 0, 0, 0, 0]) == :absent

      assert {:ok, record} = LaunchAbi.launch_record(Enum.map(1..5, &(&1 * 0x1111)))
      assert record.launcher == "0x0000000000000000000000000000000000001111"
      assert record.treasury == "0x0000000000000000000000000000000000005555"
    end

    test "a malformed record and a partly zero one are neither absent nor a launch" do
      assert LaunchAbi.launch_record([1, 2, 3]) == :error
      assert LaunchAbi.launch_record([1, 0, 3, 4, 5]) == :error
    end
  end

  # Helpers

  defp assert_matches_cast(params) do
    assert LaunchAbi.encode_launch(params) ==
             cast(["calldata", LaunchAbi.signature(:launch), tuple(params)])
  end

  defp tuple(params) do
    "(" <>
      Enum.map_join(
        [
          quoted(params.name),
          quoted(params.symbol),
          quoted(params.description),
          quoted(params.website),
          quoted(params.image),
          params.treasury,
          Integer.to_string(params.required_regent_raised),
          Integer.to_string(params.expected_launch_fee)
        ],
        ",",
        & &1
      ) <> ")"
  end

  defp quoted(value), do: ~s("#{value}")

  # One returned word, produced by Foundry from a signed value, so the decoder is
  # tested against the sign extension a real provider would send.
  defp word(value) do
    ["abi-encode", "spacing(int24)", value]
    |> cast()
    |> String.trim_leading("0x")
    |> String.to_integer(16)
  end

  defp cast(args) do
    executable = System.find_executable("cast") || flunk("Foundry cast is required for ABI proof")
    {output, 0} = System.cmd(executable, args, stderr_to_stdout: true)
    String.trim(output)
  end
end
