[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  path = "/healthz"
  protocol = "http"
  timeout = "2s"
