defmodule RegentsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :regents

  # A connected mount reads the cookie the socket handshake carried, so the
  # transport must decode it with the same options the request plug runs with.
  @session_options {Application, :fetch_env!, [:regents, :session_options]}

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :uri, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :uri, session: @session_options]]

  plug RegentsWeb.Plugs.CanonicalHost
  plug RegentsWeb.Plugs.ContractHeaders

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :regents,
    gzip: not code_reloading?,
    only: RegentsWeb.static_paths(),
    only_matching: RegentsWeb.digested_static_prefixes(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Before the parsers, so a body they reject on an /api path is answered in
  # JSON like every other API error.
  plug RegentAgentAccess.Plug,
    documents: &RegentsWeb.PublicDocuments.document/1,
    guide: "/llms.txt"

  plug RegentsWeb.Plugs.Parsers,
    body_reader: {RegentsWeb.Plugs.AgentBodyReader, :read_body, []},
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug RegentsWeb.Plugs.RuntimeSession
  plug RegentsWeb.Router
end
