import {readFileSync} from "node:fs"

import {resolveShader} from "@vgpu/wgsl/runtime"
import {beforeEach, describe, expect, it, vi} from "vitest"

const gpuCalls = vi.hoisted(() => ({
  draws: [] as Array<Record<string, unknown>>,
  geometries: [] as Array<Record<string, unknown>>,
}))

vi.mock("vgpu", () => ({
  draw: vi.fn((_gpu: unknown, options: Record<string, unknown>) => {
    gpuCalls.draws.push(options)
    return {compile: vi.fn(), set: vi.fn()}
  }),
  effect: vi.fn(() => ({compile: vi.fn(), set: vi.fn()})),
  frame: vi.fn(),
  geometry: vi.fn((_gpu: unknown, options: Record<string, unknown>) => {
    const value = {options, destroy: vi.fn()}
    gpuCalls.geometries.push(value)
    return value
  }),
  sampler: vi.fn(() => ({})),
  target: vi.fn(),
}))

vi.mock("vgpu/scene", () => ({
  perspectiveCamera: vi.fn(() => ({viewProjection: new Float32Array(16)})),
}))

import {
  CROWN_FRAME_MARGIN,
  cameraView,
  crownCameraDistance,
  rotationMatrix,
} from "../js/home_prism/camera"
import {
  CROWN_VERTEX_FLOATS,
  crownMeshData,
} from "../js/home_prism/crown-mesh"
import {
  CAMERA_FOV_DEGREES,
  CAMERA_ORBIT_DEGREES,
  CAMERA_ORBIT_LERP,
  CROWN_AABB_CORNERS,
  CROWN_BACK_Z,
  CROWN_CELL_CENTERS,
  CROWN_CELL_COUNT,
  CROWN_FRONT_Z,
  CROWN_GLASS,
  CROWN_GRID,
  CROWN_HALF_SIZE,
  type Vec3,
} from "../js/home_prism/crown-types"
import {createScene, destroyScene} from "../js/home_prism/scene"

const readText = (url: URL): string => new TextDecoder().decode(readFileSync(url))
const sourceRoot = new URL("../js/home_prism/shaders/source/", import.meta.url)
const vendorColor = new URL("../../node_modules/@vgpu/wgsl-std/src/color/index.wgsl", import.meta.url)
const sha256 = async (value: string): Promise<string> => {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))
  return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join("")
}

const expectedShaderDigests = {
  "/regents/home-crown/crown-glass-front.wgsl":
    "2522c4ecd14b3966c5278f01689f82b08291bb80561557bda5d82198c2191bac",
  "/regents/home-crown/crown-glass-back.wgsl":
    "f1ef00628482d8e7ddfb2e41c4c86ac5fdd31a58f32e2b6246a5fdd241d21df5",
  "/regents/home-crown/crown-glass-common.wgsl":
    "aa0df4059483fd58b9fd181cb8465304a5125b2934128eaa9f932b74d93d0de4",
  "/regents/home-crown/environment.wgsl":
    "382157376c95468a7a9ad1b5c50ba4d630aa3ec15589e7c86041b074d6f54d90",
  "/vendor/@vgpu/wgsl-std/color/index.wgsl":
    "9a65713c22469c7aea102286385e00d5ac8c5986bb415384af779c04fbf88401",
} as const

const moduleFile = {
  "/regents/home-crown/crown-glass-front.wgsl": new URL("crown-glass-front.wgsl", sourceRoot),
  "/regents/home-crown/crown-glass-back.wgsl": new URL("crown-glass-back.wgsl", sourceRoot),
  "/regents/home-crown/crown-glass-common.wgsl": new URL("crown-glass-common.wgsl", sourceRoot),
  "/regents/home-crown/environment.wgsl": new URL("environment.wgsl", sourceRoot),
  "/vendor/@vgpu/wgsl-std/color/index.wgsl": vendorColor,
} as const

const shaderModules = Object.fromEntries(
  Object.entries(moduleFile).map(([key, file]) => [key, readText(file)]),
) as Record<keyof typeof moduleFile, string>

const commonShaderSources = [
  "/regents/home-crown/crown-glass-common.wgsl",
  "/regents/home-crown/environment.wgsl",
  "/vendor/@vgpu/wgsl-std/color/index.wgsl",
] as const

function generatedShaderModule(entry: keyof typeof moduleFile, wgsl: string): string {
  const sources = [entry, ...commonShaderSources]
  return `/**
 * Generated offline from versioned WGSL. Do not edit this file directly.
 * Entry: ${entry}
 * Inputs:
${sources.map(source => ` *   ${source}  sha256:${expectedShaderDigests[source]}`).join("\n")}
 * Resolver: @vgpu/wgsl 0.3.1 resolveShader(), validate: "off", minify: false.
 * Canonical virtual paths are resolved in memory; no path rewriting follows resolution.
 */

export default {version: 1, wgsl: ${JSON.stringify(wgsl)}} as const
`
}

const position = (vertices: Float32Array<ArrayBuffer>, index: number): Vec3 => {
  const offset = index * CROWN_VERTEX_FLOATS
  return [vertices[offset]!, vertices[offset + 1]!, vertices[offset + 2]!]
}

const subtract = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
const cross = (a: Vec3, b: Vec3): Vec3 => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0],
]
const dot = (a: Vec3, b: Vec3): number => a[0] * b[0] + a[1] * b[1] + a[2] * b[2]

describe("Regents crown geometry invariants", () => {
  it("keeps the exact ordered 3 / 5 / 5 cell centers", () => {
    expect(CROWN_GRID).toEqual([
      [-2, 1], [0, 1], [2, 1],
      [-2, 0], [-1, 0], [0, 0], [1, 0], [2, 0],
      [-2, -1], [-1, -1], [0, -1], [1, -1], [2, -1],
    ])
    expect(CROWN_CELL_CENTERS).toEqual([
      [-0.49, 0.245], [0, 0.245], [0.49, 0.245],
      [-0.49, 0], [-0.245, 0], [0, 0], [0.245, 0], [0.49, 0],
      [-0.49, -0.245], [-0.245, -0.245], [0, -0.245], [0.245, -0.245], [0.49, -0.245],
    ])
    expect(CROWN_CELL_CENTERS).toHaveLength(CROWN_CELL_COUNT)
  })

  it("builds 3,146 vertices and 5,200 nondegenerate outward triangles", () => {
    const mesh = crownMeshData()
    expect(mesh.vertices.length / CROWN_VERTEX_FLOATS).toBe(3_146)
    expect(mesh.indices).toHaveLength(15_600)
    expect(mesh.indices.length / 3).toBe(5_200)

    const centers = new Set<string>()
    for (let offset = 0; offset < mesh.indices.length; offset += 3) {
      const ids = [mesh.indices[offset]!, mesh.indices[offset + 1]!, mesh.indices[offset + 2]!]
      const cellCenters = ids.map(index => {
        const vertex = index * CROWN_VERTEX_FLOATS
        return [mesh.vertices[vertex + 6]!, mesh.vertices[vertex + 7]!] as const
      })
      expect(cellCenters[1]).toEqual(cellCenters[0])
      expect(cellCenters[2]).toEqual(cellCenters[0])
      centers.add(cellCenters[0]!.join(","))

      const [a, b, c] = ids.map(index => position(mesh.vertices, index)) as [Vec3, Vec3, Vec3]
      const normal = cross(subtract(b, a), subtract(c, a))
      expect(Math.hypot(...normal)).toBeGreaterThan(1e-9)
      const centroid: Vec3 = [
        (a[0] + b[0] + c[0]) / 3,
        (a[1] + b[1] + c[1]) / 3,
        (a[2] + b[2] + c[2]) / 3,
      ]
      const solidCenter: Vec3 = [
        cellCenters[0]![0],
        cellCenters[0]![1],
        (CROWN_BACK_Z + CROWN_FRONT_Z) / 2,
      ]
      expect(dot(normal, subtract(centroid, solidCenter))).toBeGreaterThan(0)
    }
    expect(centers.size).toBe(13)
  })

  it("forms thirteen welded connected solids contained in their ideal cubes", () => {
    const mesh = crownMeshData()
    const vertexCount = mesh.vertices.length / CROWN_VERTEX_FLOATS
    const parent = Array.from({length: vertexCount}, (_, index) => index)
    const find = (index: number): number => {
      while (parent[index] !== index) {
        parent[index] = parent[parent[index]!]!
        index = parent[index]!
      }
      return index
    }
    const unite = (left: number, right: number) => {
      const a = find(left)
      const b = find(right)
      if (a !== b) parent[b] = a
    }

    const coincident = new Map<string, number>()
    for (let index = 0; index < vertexCount; index += 1) {
      const offset = index * CROWN_VERTEX_FLOATS
      const [x, y, z] = position(mesh.vertices, index)
      const cx = mesh.vertices[offset + 6]!
      const cy = mesh.vertices[offset + 7]!
      expect(Math.abs(x - cx)).toBeLessThanOrEqual(CROWN_HALF_SIZE + 1e-6)
      expect(Math.abs(y - cy)).toBeLessThanOrEqual(CROWN_HALF_SIZE + 1e-6)
      expect(z).toBeGreaterThanOrEqual(CROWN_BACK_Z - 1e-6)
      expect(z).toBeLessThanOrEqual(CROWN_FRONT_Z + 1e-6)

      const key = [x, y, z, cx, cy].join(":")
      const first = coincident.get(key)
      if (first === undefined) coincident.set(key, index)
      else unite(first, index)
    }
    for (let offset = 0; offset < mesh.indices.length; offset += 3) {
      unite(mesh.indices[offset]!, mesh.indices[offset + 1]!)
      unite(mesh.indices[offset + 1]!, mesh.indices[offset + 2]!)
    }
    expect(new Set(mesh.indices.map(index => find(index))).size).toBe(13)
  })
})

describe("Regents crown scene ownership", () => {
  beforeEach(() => {
    gpuCalls.draws.length = 0
    gpuCalls.geometries.length = 0
  })

  it("uses exactly one indexed crown geometry for both glass draws", () => {
    const scene = createScene({} as never, [390, 844], "crown-test")
    expect(gpuCalls.geometries).toHaveLength(1)
    const glassDraws = gpuCalls.draws.filter(draw =>
      ["crown-test.glass-back", "crown-test.glass-front"].includes(draw.label as string),
    )
    expect(glassDraws).toHaveLength(2)
    expect(glassDraws[0]!.geometry).toBe(scene.crown)
    expect(glassDraws[1]!.geometry).toBe(scene.crown)
    expect(gpuCalls.draws.map(draw => draw.label)).not.toContain("crown-test.light")
    expect(gpuCalls.draws.some(draw => String(draw.label).includes("wireframe"))).toBe(false)

    destroyScene(scene)
    expect(scene.crown.destroy).toHaveBeenCalledTimes(1)
  })

  it("aims the fixed studio key at the crown's front faces", () => {
    const rotation = rotationMatrix(CROWN_GLASS.environmentRotation)
    const reflectedFront: Vec3 = [rotation[8]!, rotation[9]!, rotation[10]!]
    const studioKey = [0.612, 0.354, 0.707] as const
    expect(dot(reflectedFront, studioKey)).toBeGreaterThan(0.995)
    expect(CROWN_GLASS.environmentExposure).toBe(0.8)
    expect(CROWN_GLASS.iridescenceStrength).toBe(0.02)
  })

  it("keeps triangle tracer, light, and wireframe modules outside the live closure", () => {
    const entry = new URL("../js/home_prism/index.ts", import.meta.url)
    const closure = new Set<string>()
    const visit = (file: URL) => {
      if (closure.has(file.href)) return
      closure.add(file.href)
      const source = readText(file)
      for (const match of source.matchAll(/(?:from\s+|import\s*\()["'](\.[^"']+)["']/g)) {
        const base = new URL(match[1]!, file)
        const imported = [base, new URL(`${base.href}.ts`), new URL(`${base.href}/index.ts`)].find(
          candidate => {
            try {
              readFileSync(candidate)
              return true
            } catch {
              return false
            }
          },
        )
        if (imported) visit(imported)
      }
    }
    visit(entry)

    for (const forbidden of [
      "/assets/js/home_prism/light-mesh.ts",
      "/assets/js/home_prism/optics.ts",
      "/assets/js/home_prism/prism-mesh.ts",
      "/assets/js/home_prism/shaders/light.ts",
      "/assets/js/home_prism/shaders/glass.ts",
      "/assets/js/home_prism/shaders/glass-back.ts",
      "/assets/js/home_prism/types.ts",
    ]) {
      expect([...closure].some(file => file.endsWith(forbidden))).toBe(false)
    }

    const liveSource = [...closure].map(file => readText(new URL(file))).join("\n")
    for (const forbidden of [
      "buildLightMesh",
      "tracePrismDetailed",
      "setLampAim",
      "lightBuffer",
      "crownWireframeGeometry",
      "uniqueWireframeIndices",
    ]) {
      expect(liveSource).not.toContain(forbidden)
    }
  })
})

describe("Regents crown shader provenance", () => {
  it("matches every fixed raw digest and regenerates committed modules byte-for-byte", async () => {
    for (const [source, digest] of Object.entries(expectedShaderDigests)) {
      expect(await sha256(shaderModules[source as keyof typeof moduleFile])).toBe(digest)
    }

    for (const face of ["front", "back"] as const) {
      const entry = `/regents/home-crown/crown-glass-${face}.wgsl` as const
      const resolved = await resolveShader({
        entry,
        modules: shaderModules,
        packageMap: {"@vgpu/wgsl-std": "/vendor/@vgpu/wgsl-std"},
        validate: "off",
        minify: false,
      })
      expect(resolved.sourceMap.sources).toEqual([entry, ...commonShaderSources])
      for (const source of resolved.sourceMap.sources) {
        expect(resolved.wgsl).toContain(`// vgsl-module: ${source}`)
      }
      const committed = readText(
        new URL(`../js/home_prism/shaders/crown-glass-${face}.ts`, import.meta.url),
      )
      expect(committed).toBe(generatedShaderModule(entry, resolved.wgsl))
    }
  })
})

describe("Regents crown responsive framing", () => {
  it("keeps every 3D AABB corner at least eight percent from every edge", () => {
    expect(CROWN_FRAME_MARGIN).toBe(0.08)
    expect(CROWN_AABB_CORNERS).toHaveLength(8)
    const tanHalfFov = Math.tan((CAMERA_FOV_DEGREES * Math.PI) / 360)
    const sizes = [
      [320, 720],
      [390, 844],
      [1440, 900],
      [2560, 1080],
    ] as const

    for (const [width, height] of sizes) {
      const aspect = width / height
      for (const orbitX of [-1, 1]) {
        for (const orbitY of [-1, 1]) {
          const view = cameraView(aspect, orbitX, orbitY)
          expect(Math.hypot(...view.position)).toBeCloseTo(crownCameraDistance(aspect), 12)
          for (const corner of CROWN_AABB_CORNERS) {
            const relative = subtract(corner, view.position)
            const depth = dot(relative, view.forward)
            expect(depth).toBeGreaterThan(0)
            const ndcX = dot(relative, view.right) / (depth * tanHalfFov * aspect)
            const ndcY = dot(relative, view.up) / (depth * tanHalfFov)
            const screenX = (ndcX + 1) / 2
            const screenY = (1 - ndcY) / 2
            expect(Math.min(screenX, 1 - screenX)).toBeGreaterThanOrEqual(CROWN_FRAME_MARGIN)
            expect(Math.min(screenY, 1 - screenY)).toBeGreaterThanOrEqual(CROWN_FRAME_MARGIN)
          }
        }
      }
    }
  })

  it("derives a fresh fit across resize while preserving the reviewed motion bound", () => {
    const resizeSequence = [[320, 720], [2560, 1080], [390, 844], [1440, 900]] as const
    const distances = resizeSequence.map(([width, height]) => crownCameraDistance(width / height))
    expect(distances[0]).toBeGreaterThan(distances[1]!)
    expect(distances[2]).toBeGreaterThan(distances[3]!)
    expect(CAMERA_ORBIT_DEGREES).toBe(3.5)
    expect(CAMERA_ORBIT_LERP).toBe(0.08)
  })
})
