defmodule AshPlatform.Repo.Migrations.RegentZs63TechtreePublicReadIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:nodes, [:tree_id, "published_at DESC", "id ASC"],
             name: "nodes_public_tree_page_index",
             concurrently: true,
             prefix: "techtree"
           )
  end

  def down do
    drop_if_exists(
      index(:nodes, [:tree_id, "published_at DESC", "id ASC"],
        name: "nodes_public_tree_page_index",
        prefix: "techtree"
      )
    )
  end
end
