defmodule Regents.Repo.Migrations.AddArticleAuthors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:blog_posts) do
      add(:authors, {:array, :map}, null: false, default: [])
      add(:published_by, :bigint)
    end
  end

  def down do
    alter table(:blog_posts) do
      remove(:published_by)
      remove(:authors)
    end
  end
end
