defmodule AshPlatform.Repo.Migrations.AddPrepaidAuthorizationKernel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:billing_spend_reservations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:operation_key, :text, null: false)
      add(:amount_cents, :bigint, null: false)
      add(:consumed_cents, :bigint, null: false, default: 0)
      add(:status, :text, null: false, default: "active")

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:billing_account_id, :uuid, null: false)
    end

    create index(:billing_spend_reservations, [:billing_account_id, :status])

    create unique_index(:billing_spend_reservations, [:operation_key],
             name: "billing_spend_reservations_globally_unique_operation_key_index"
           )

    create table(:billing_ledger_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:idempotency_key, :text, null: false)
      add(:provider_reference, :text)
      add(:reservation_id, :uuid)
      add(:amount_cents, :bigint, null: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:billing_account_id, :uuid, null: false)
    end

    create index(:billing_ledger_entries, [:billing_account_id, :created_at])

    create index(:billing_ledger_entries, [:provider_reference],
             unique: true,
             where: "provider_reference IS NOT NULL"
           )

    create unique_index(:billing_ledger_entries, [:idempotency_key],
             name: "billing_ledger_entries_globally_unique_idempotency_key_index"
           )

    create table(:billing_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:billing_spend_reservations) do
      modify(
        :billing_account_id,
        references(:billing_accounts,
          column: :id,
          name: "billing_spend_reservations_billing_account_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:billing_ledger_entries) do
      modify(
        :billing_account_id,
        references(:billing_accounts,
          column: :id,
          name: "billing_ledger_entries_billing_account_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:billing_accounts) do
      add(:currency, :text, null: false, default: "usd")
      add(:funded_cents, :bigint, null: false, default: 0)
      add(:reserved_cents, :bigint, null: false, default: 0)
      add(:consumed_cents, :bigint, null: false, default: 0)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "billing_accounts_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)
    end

    create unique_index(:billing_accounts, [:human_account_id],
             name: "billing_accounts_one_per_human_account_index"
           )

    create constraint(:billing_accounts, :billing_accounts_funded_non_negative,
             check: """
               funded_cents >= 0
             """
           )

    create constraint(:billing_accounts, :billing_accounts_reserved_non_negative,
             check: """
               reserved_cents >= 0
             """
           )

    create constraint(:billing_accounts, :billing_accounts_consumed_non_negative,
             check: """
               consumed_cents >= 0
             """
           )

    create constraint(:billing_accounts, :billing_accounts_authority_balanced,
             check: """
               funded_cents >= reserved_cents + consumed_cents
             """
           )

    create constraint(:billing_ledger_entries, :billing_ledger_entries_amount_positive,
             check: """
               amount_cents > 0
             """
           )

    create constraint(:billing_spend_reservations, :billing_spend_reservations_amount_positive,
             check: """
               amount_cents > 0
             """
           )

    create constraint(:billing_spend_reservations, :billing_spend_reservations_consumed_valid,
             check: """
               consumed_cents >= 0 AND consumed_cents <= amount_cents
             """
           )
  end

  def down do
    drop_if_exists(
      constraint(:billing_spend_reservations, :billing_spend_reservations_consumed_valid)
    )

    drop_if_exists(
      constraint(:billing_spend_reservations, :billing_spend_reservations_amount_positive)
    )

    drop_if_exists(constraint(:billing_ledger_entries, :billing_ledger_entries_amount_positive))

    drop_if_exists(constraint(:billing_accounts, :billing_accounts_authority_balanced))

    drop_if_exists(constraint(:billing_accounts, :billing_accounts_consumed_non_negative))

    drop_if_exists(constraint(:billing_accounts, :billing_accounts_reserved_non_negative))

    drop_if_exists(constraint(:billing_accounts, :billing_accounts_funded_non_negative))

    drop(constraint(:billing_accounts, "billing_accounts_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:billing_accounts, [:human_account_id],
        name: "billing_accounts_one_per_human_account_index"
      )
    )

    alter table(:billing_accounts) do
      remove(:human_account_id)
      remove(:updated_at)
      remove(:created_at)
      remove(:consumed_cents)
      remove(:reserved_cents)
      remove(:funded_cents)
      remove(:currency)
    end

    drop(constraint(:billing_ledger_entries, "billing_ledger_entries_billing_account_id_fkey"))

    alter table(:billing_ledger_entries) do
      modify(:billing_account_id, :uuid)
    end

    drop(
      constraint(
        :billing_spend_reservations,
        "billing_spend_reservations_billing_account_id_fkey"
      )
    )

    alter table(:billing_spend_reservations) do
      modify(:billing_account_id, :uuid)
    end

    drop(table(:billing_accounts))

    drop_if_exists(
      unique_index(:billing_ledger_entries, [:idempotency_key],
        name: "billing_ledger_entries_globally_unique_idempotency_key_index"
      )
    )

    drop_if_exists(index(:billing_ledger_entries, [:provider_reference]))

    drop_if_exists(index(:billing_ledger_entries, [:billing_account_id, :created_at]))

    drop(table(:billing_ledger_entries))

    drop_if_exists(
      unique_index(:billing_spend_reservations, [:operation_key],
        name: "billing_spend_reservations_globally_unique_operation_key_index"
      )
    )

    drop_if_exists(index(:billing_spend_reservations, [:billing_account_id, :status]))

    drop(table(:billing_spend_reservations))
  end
end
