defmodule AshPlatform.Repo.Migrations.Regent49052C4LaunchOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:launch_operations, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action_id, :text, null: false)
      add(:envelope, :map, null: false)
      add(:signer, :text, null: false)
      add(:step, :text, null: false)
      add(:state, :text, null: false, default: "prepared")
      add(:approval_transaction_hash, :text)
      add(:launch_transaction_hash, :text)
      add(:result, :map, default: %{})
      add(:reason, :text)
      add(:terminal_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "launch_operations_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ), null: false)

      add(
        :launch_draft_id,
        references(:launch_drafts,
          column: :id,
          name: "launch_operations_launch_draft_id_fkey",
          type: :uuid,
          prefix: "autolaunch",
          on_delete: :restrict
        ), null: false)
    end

    create unique_index(:launch_operations, [:human_account_id],
             name: "launch_operations_one_open_per_account_index",
             prefix: "autolaunch",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:launch_operations, [:action_id],
             name: "launch_operations_unique_launch_action_id_index",
             prefix: "autolaunch"
           )

    create unique_index(:launch_operations, [:approval_transaction_hash],
             name: "launch_operations_unique_launch_approval_hash_index",
             prefix: "autolaunch"
           )

    create unique_index(:launch_operations, [:launch_transaction_hash],
             name: "launch_operations_unique_launch_hash_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop(
      constraint(:launch_operations, "launch_operations_human_account_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop(
      constraint(:launch_operations, "launch_operations_launch_draft_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_operations, [:launch_transaction_hash],
        name: "launch_operations_unique_launch_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_operations, [:approval_transaction_hash],
        name: "launch_operations_unique_launch_approval_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_operations, [:action_id],
        name: "launch_operations_unique_launch_action_id_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_operations, [:human_account_id],
        name: "launch_operations_one_open_per_account_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:launch_operations, prefix: "autolaunch"))
  end
end
