defmodule AshPlatform.Repo.Migrations.AddTechtreeEdgesAndNodeLayout do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nodes, prefix: "techtree") do
      add(:pos_x, :float)
      add(:pos_y, :float)
      add(:display_kind, :text, null: false, default: "standard")
    end

    execute("CREATE SCHEMA IF NOT EXISTS techtree")

    create table(:edges, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false, default: "prerequisite")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :from_node_id,
        references(:nodes,
          column: :id,
          name: "edges_from_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ), null: false)

      add(
        :to_node_id,
        references(:nodes,
          column: :id,
          name: "edges_to_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ), null: false)
    end

    create unique_index(:edges, [:from_node_id, :to_node_id],
             name: "edges_unique_pair_index",
             prefix: "techtree"
           )
  end

  def down do
    drop(constraint(:edges, "edges_from_node_id_fkey", prefix: "techtree"))

    drop(constraint(:edges, "edges_to_node_id_fkey", prefix: "techtree"))

    drop_if_exists(
      unique_index(:edges, [:from_node_id, :to_node_id],
        name: "edges_unique_pair_index",
        prefix: "techtree"
      )
    )

    drop(table(:edges, prefix: "techtree"))

    alter table(:nodes, prefix: "techtree") do
      remove(:display_kind)
      remove(:pos_y)
      remove(:pos_x)
    end
  end
end
