defmodule AshPlatform.Repo.Migrations.RegentZs66TechtreeProvenancePayload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nodes, prefix: "techtree") do
      add(:manifest_cid, :text)
      add(:manifest_hash, :text)
      add(:manifest_uri, :text)
      add(:lineage, :map)
      add(:projection_status, :text, null: false, default: "not_started")
    end
  end

  def down do
    alter table(:nodes, prefix: "techtree") do
      remove(:projection_status)
      remove(:lineage)
      remove(:manifest_uri)
      remove(:manifest_hash)
      remove(:manifest_cid)
    end
  end
end
