defmodule AshPlatform.Repo.Migrations.RegentZs63TechtreeWorkflowState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nodes, prefix: "techtree") do
      add(:workflow_state, :text, null: false, default: "published")
    end
  end

  def down do
    alter table(:nodes, prefix: "techtree") do
      remove(:workflow_state)
    end
  end
end
