defmodule AshPlatform.Repo.Migrations.CreateTechtreeTreesAndNodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS techtree")

    create table(:trees, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:name, :text, null: false)
      add(:description, :text, null: false)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:trees, [:position],
             name: "trees_unique_position_index",
             prefix: "techtree"
           )

    create unique_index(:trees, [:slug], name: "trees_unique_slug_index", prefix: "techtree")

    execute("CREATE SCHEMA IF NOT EXISTS techtree")

    create table(:nodes, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:summary, :text)
      add(:payload_hash, :text)

      add(:published_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :tree_id,
        references(:trees,
          column: :id,
          name: "nodes_tree_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:nodes, "nodes_tree_id_fkey", prefix: "techtree"))

    drop(table(:nodes, prefix: "techtree"))

    drop_if_exists(
      unique_index(:trees, [:slug], name: "trees_unique_slug_index", prefix: "techtree")
    )

    drop_if_exists(
      unique_index(:trees, [:position], name: "trees_unique_position_index", prefix: "techtree")
    )

    drop(table(:trees, prefix: "techtree"))
  end
end
