defmodule AshPlatform.Repo.Migrations.AddTechtreeCommentReactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS discussions")

    create table(:comment_reactions, primary_key: false, prefix: "discussions") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :comment_id,
        references(:comments,
          column: :id,
          name: "comment_reactions_comment_id_fkey",
          type: :uuid,
          prefix: "discussions"
        ), null: false)

      add(
        :reactor_id,
        references(:platform_human_users,
          column: :id,
          name: "comment_reactions_reactor_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)
    end

    create unique_index(:comment_reactions, [:reactor_id, :comment_id],
             name: "comment_reactions_unique_reactor_comment_index",
             prefix: "discussions"
           )
  end

  def down do
    drop(
      constraint(:comment_reactions, "comment_reactions_comment_id_fkey", prefix: "discussions")
    )

    drop(
      constraint(:comment_reactions, "comment_reactions_reactor_id_fkey", prefix: "discussions")
    )

    drop_if_exists(
      unique_index(:comment_reactions, [:reactor_id, :comment_id],
        name: "comment_reactions_unique_reactor_comment_index",
        prefix: "discussions"
      )
    )

    drop(table(:comment_reactions, prefix: "discussions"))
  end
end
