defmodule AshPlatform.Repo.Migrations.AddAutolaunchBidPreparedActionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bids, prefix: "autolaunch") do
      add(:auction_address, :text)
      add(:onchain_bid_id, :text)
    end

    alter table(:auctions, prefix: "autolaunch") do
      add(:auction_address, :text)
      add(:quote_token_address, :text)
      add(:quote_token_symbol, :text)
      add(:quote_token_decimals, :bigint)
      add(:current_clearing_price, :text)
    end
  end

  def down do
    alter table(:auctions, prefix: "autolaunch") do
      remove(:current_clearing_price)
      remove(:quote_token_decimals)
      remove(:quote_token_symbol)
      remove(:quote_token_address)
      remove(:auction_address)
    end

    alter table(:bids, prefix: "autolaunch") do
      remove(:onchain_bid_id)
      remove(:auction_address)
    end
  end
end
