defmodule AshPlatform.Repo.Migrations.AddFormationCloudRuntimes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cloud_runtimes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_sprite_id, :text, null: false)
      add(:sprite_name, :text, null: false)
      add(:url, :text, null: false)
      add(:provider_status, :text, null: false)
      add(:observed_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "cloud_runtimes_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)

      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "cloud_runtimes_regent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:cloud_runtimes, [:human_account_id])

    create unique_index(:cloud_runtimes, [:provider_sprite_id],
             name: "cloud_runtimes_unique_provider_sprite_index"
           )

    create unique_index(:cloud_runtimes, [:regent_id], name: "cloud_runtimes_unique_regent_index")

    create unique_index(:cloud_runtimes, [:sprite_name],
             name: "cloud_runtimes_unique_sprite_name_index"
           )
  end

  def down do
    drop(constraint(:cloud_runtimes, "cloud_runtimes_human_account_id_fkey"))

    drop(constraint(:cloud_runtimes, "cloud_runtimes_regent_id_fkey"))

    drop_if_exists(
      unique_index(:cloud_runtimes, [:sprite_name],
        name: "cloud_runtimes_unique_sprite_name_index"
      )
    )

    drop_if_exists(
      unique_index(:cloud_runtimes, [:regent_id], name: "cloud_runtimes_unique_regent_index")
    )

    drop_if_exists(
      unique_index(:cloud_runtimes, [:provider_sprite_id],
        name: "cloud_runtimes_unique_provider_sprite_index"
      )
    )

    drop_if_exists(index(:cloud_runtimes, [:human_account_id]))

    drop(table(:cloud_runtimes))
  end
end
