defmodule AshPlatform.Repo.Migrations.AddAutolaunchSubjectsAndActions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:subjects, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:subject_kind, :text, null: false)
      add(:chain_id, :bigint, null: false)
      add(:token_address, :text)
      add(:splitter_address, :text)
      add(:ingress_address, :text)
      add(:treasury_address, :text)
      add(:factory_address, :text)
      add(:creator_address, :text)
      add(:staker_pool_bps, :bigint)
      add(:protocol_skim_bps_snapshot, :bigint)
      add(:current_protocol_skim_bps, :bigint)
      add(:protocol_fee_usdc_total_raw, :text)
      add(:regent_emission_total_raw, :text)
      add(:pending_buyback_usdc_raw, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:subject_actions, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action, :text, null: false)
      add(:owner_address, :text)
      add(:chain_id, :bigint, null: false)
      add(:tx_hash, :text)
      add(:amount, :text)
      add(:status, :text, null: false, default: "pending")
      add(:block_number, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :subject_id,
        references(:subjects,
          column: :id,
          name: "subject_actions_subject_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:subject_actions, "subject_actions_subject_id_fkey", prefix: "autolaunch"))

    drop(table(:subject_actions, prefix: "autolaunch"))

    drop(table(:subjects, prefix: "autolaunch"))
  end
end
