defmodule AshPlatform.Repo.Migrations.AddAutolaunchSubjectIdAndTokenLinkage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tokens, prefix: "autolaunch") do
      add(:subject_id, :text)
    end

    alter table(:subjects, prefix: "autolaunch") do
      add(:subject_id, :text, null: false)
    end

    create unique_index(:subjects, [:subject_id],
             name: "subjects_unique_subject_id_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:subjects, [:subject_id],
        name: "subjects_unique_subject_id_index",
        prefix: "autolaunch"
      )
    )

    alter table(:subjects, prefix: "autolaunch") do
      remove(:subject_id)
    end

    alter table(:tokens, prefix: "autolaunch") do
      remove(:subject_id)
    end
  end
end
