defmodule AshPlatform.Repo.Migrations.AddTechtreeNotebookArtifacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS techtree")

    create table(:notebook_artifacts, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:node_payload_hash, :text, null: false)
      add(:source_hash, :text, null: false)
      add(:payload_hash, :text, null: false)
      add(:marimo_version, :text, null: false)
      add(:runtime, :text, null: false, default: "pyodide")
      add(:compatibility, :text, null: false, default: "verified")
      add(:run_url, :text, null: false)
      add(:manifest_json, :text, null: false)
      add(:allowed_assets, {:array, :text}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :node_id,
        references(:nodes,
          column: :id,
          name: "notebook_artifacts_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ), null: false)
    end

    create unique_index(:notebook_artifacts, [:node_id, :node_payload_hash, :source_hash],
             name: "notebook_artifacts_unique_node_source_index",
             prefix: "techtree"
           )
  end

  def down do
    drop(constraint(:notebook_artifacts, "notebook_artifacts_node_id_fkey", prefix: "techtree"))

    drop_if_exists(
      unique_index(:notebook_artifacts, [:node_id, :node_payload_hash, :source_hash],
        name: "notebook_artifacts_unique_node_source_index",
        prefix: "techtree"
      )
    )

    drop(table(:notebook_artifacts, prefix: "techtree"))
  end
end
