defmodule AshPlatform.Repo.Migrations.AddAutolaunchLaunchDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:launch_drafts, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:token_name, :text, null: false)
      add(:symbol, :text, null: false)
      add(:summary, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "launch_drafts_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)

      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "launch_drafts_regent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:launch_drafts, [:regent_id], prefix: "autolaunch")

    create index(:launch_drafts, [:human_account_id], prefix: "autolaunch")
  end

  def down do
    drop(constraint(:launch_drafts, "launch_drafts_human_account_id_fkey", prefix: "autolaunch"))

    drop(constraint(:launch_drafts, "launch_drafts_regent_id_fkey", prefix: "autolaunch"))

    drop_if_exists(index(:launch_drafts, [:human_account_id], prefix: "autolaunch"))

    drop_if_exists(index(:launch_drafts, [:regent_id], prefix: "autolaunch"))

    drop(table(:launch_drafts, prefix: "autolaunch"))
  end
end
