defmodule AshPlatform.Repo.Migrations.AddPublicRegentProfileProjection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:regents) do
      add(:avatar_url, :text)
    end
  end

  def down do
    alter table(:regents) do
      remove(:avatar_url)
    end
  end
end
