defmodule AshPlatform.Repo.Migrations.InitialRegentsApp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # The regents table comes first by hand: the generator ordered tables by
    # name, but agent_links, agent_pairing_codes and cloud_runtimes reference it.
    create table(:regents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:display_name, :text, null: false)
      add(:summary, :text)
      add(:avatar_url, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "regents_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:regents, [:human_account_id], name: "regents_unique_human_account_index")

    create unique_index(:regents, [:slug], name: "regents_unique_slug_index")

    create table(:account_ens_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ens_name, :text)
      add(:ens_avatar_url, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "account_ens_identities_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:account_ens_identities, [:human_account_id],
             name: "account_ens_identities_unique_human_account_index"
           )

    create table(:agent_links, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:agent_id, :text, null: false)
      add(:registry_address, :text, null: false)
      add(:token_id, :text, null: false)
      add(:wallet, :text, null: false)
      add(:paired_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "agent_links_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:agent_links, [:agent_id], name: "agent_links_unique_agent_id_index")

    create unique_index(:agent_links, [:registry_address, :token_id],
             name: "agent_links_unique_registry_token_index"
           )

    alter table(:agent_links) do
      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "agent_links_regent_id_fkey",
          type: :uuid,
          prefix: "regents_app"
        ),
        null: false
      )
    end

    create index(:agent_links, [:human_account_id])

    create index(:agent_links, [:regent_id])

    create table(:agent_pairing_codes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code_hash, :text, null: false)
      add(:issued_at, :utc_datetime_usec, null: false)
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "agent_pairing_codes_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:agent_pairing_codes, [:code_hash],
             name: "agent_pairing_codes_unique_code_hash_index"
           )

    create unique_index(:agent_pairing_codes, [:human_account_id],
             name: "agent_pairing_codes_unique_human_account_index"
           )

    alter table(:agent_pairing_codes) do
      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "agent_pairing_codes_regent_id_fkey",
          type: :uuid,
          prefix: "regents_app"
        ),
        null: false
      )
    end

    create index(:agent_pairing_codes, [:regent_id])

    create table(:cloud_runtimes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider_sprite_id, :text, null: false)
      add(:sprite_name, :text, null: false)
      add(:url, :text, null: false)
      add(:provider_status, :text, null: false)
      add(:observed_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "cloud_runtimes_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:cloud_runtimes, [:provider_sprite_id],
             name: "cloud_runtimes_unique_provider_sprite_index"
           )

    create unique_index(:cloud_runtimes, [:sprite_name],
             name: "cloud_runtimes_unique_sprite_name_index"
           )

    alter table(:cloud_runtimes) do
      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "cloud_runtimes_regent_id_fkey",
          type: :uuid,
          prefix: "regents_app"
        ),
        null: false
      )
    end

    create unique_index(:cloud_runtimes, [:regent_id], name: "cloud_runtimes_unique_regent_index")

    create index(:cloud_runtimes, [:human_account_id])

    create table(:comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:target_type, :text, null: false)
      add(:target_id, :uuid, null: false)
      add(:body, :text, null: false)
      add(:client_request_id, :uuid, null: false)
      add(:deleted_at, :utc_datetime_usec)
      add(:deleted_by_human_account_id, :bigint)
      add(:deletion_authority, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:platform_human_users,
          column: :id,
          name: "comments_author_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:comments, [:author_id, :client_request_id],
             name: "comments_unique_author_request_index"
           )

    create table(:linked_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:subject, :text, null: false)
      add(:username, :text)
      add(:display_name, :text)
      add(:verified_at, :utc_datetime_usec, null: false)
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "linked_identities_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names"
        ),
        null: false
      )
    end

    create unique_index(:linked_identities, [:provider, :human_account_id],
             name: "linked_identities_unique_provider_per_account_index"
           )

    create unique_index(:linked_identities, [:provider, :subject],
             name: "linked_identities_unique_subject_per_provider_index"
           )

    create table(:session_authorities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:lineage_digest, :binary, null: false)
      add(:generation, :bigint, null: false, default: 0)
      add(:revoked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "session_authorities_human_account_id_fkey",
          type: :bigint,
          prefix: "regent_names",
          on_delete: :restrict
        )
      )
    end

    create unique_index(:session_authorities, [:lineage_digest],
             name: "session_authorities_unique_lineage_digest_index"
           )

    create constraint(:session_authorities, :session_authorities_generation_nonnegative,
             check: """
               generation >= 0
             """
           )
  end

  def down do
    drop_if_exists(constraint(:session_authorities, :session_authorities_generation_nonnegative))

    drop(constraint(:session_authorities, "session_authorities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:session_authorities, [:lineage_digest],
        name: "session_authorities_unique_lineage_digest_index"
      )
    )

    drop(table(:session_authorities))

    drop(constraint(:linked_identities, "linked_identities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :subject],
        name: "linked_identities_unique_subject_per_provider_index"
      )
    )

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :human_account_id],
        name: "linked_identities_unique_provider_per_account_index"
      )
    )

    drop(table(:linked_identities))

    drop(constraint(:comments, "comments_author_id_fkey"))

    drop_if_exists(
      unique_index(:comments, [:author_id, :client_request_id],
        name: "comments_unique_author_request_index"
      )
    )

    drop(table(:comments))

    drop_if_exists(index(:cloud_runtimes, [:human_account_id]))

    drop(constraint(:cloud_runtimes, "cloud_runtimes_regent_id_fkey"))

    drop(constraint(:cloud_runtimes, "cloud_runtimes_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:cloud_runtimes, [:regent_id], name: "cloud_runtimes_unique_regent_index")
    )

    alter table(:cloud_runtimes) do
      remove(:regent_id)
    end

    drop_if_exists(
      unique_index(:cloud_runtimes, [:sprite_name],
        name: "cloud_runtimes_unique_sprite_name_index"
      )
    )

    drop_if_exists(
      unique_index(:cloud_runtimes, [:provider_sprite_id],
        name: "cloud_runtimes_unique_provider_sprite_index"
      )
    )

    drop(table(:cloud_runtimes))

    drop_if_exists(index(:agent_pairing_codes, [:regent_id]))

    drop(constraint(:agent_pairing_codes, "agent_pairing_codes_regent_id_fkey"))

    drop(constraint(:agent_pairing_codes, "agent_pairing_codes_human_account_id_fkey"))

    alter table(:agent_pairing_codes) do
      remove(:regent_id)
    end

    drop_if_exists(
      unique_index(:agent_pairing_codes, [:human_account_id],
        name: "agent_pairing_codes_unique_human_account_index"
      )
    )

    drop_if_exists(
      unique_index(:agent_pairing_codes, [:code_hash],
        name: "agent_pairing_codes_unique_code_hash_index"
      )
    )

    drop(table(:agent_pairing_codes))

    drop_if_exists(index(:agent_links, [:regent_id]))

    drop_if_exists(index(:agent_links, [:human_account_id]))

    drop(constraint(:agent_links, "agent_links_regent_id_fkey"))

    drop(constraint(:agent_links, "agent_links_human_account_id_fkey"))

    alter table(:agent_links) do
      remove(:regent_id)
    end

    drop_if_exists(
      unique_index(:agent_links, [:registry_address, :token_id],
        name: "agent_links_unique_registry_token_index"
      )
    )

    drop_if_exists(
      unique_index(:agent_links, [:agent_id], name: "agent_links_unique_agent_id_index")
    )

    drop(table(:agent_links))

    drop(constraint(:account_ens_identities, "account_ens_identities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:account_ens_identities, [:human_account_id],
        name: "account_ens_identities_unique_human_account_index"
      )
    )

    drop(table(:account_ens_identities))

    drop(constraint(:regents, "regents_human_account_id_fkey"))

    drop_if_exists(unique_index(:regents, [:slug], name: "regents_unique_slug_index"))

    drop_if_exists(
      unique_index(:regents, [:human_account_id], name: "regents_unique_human_account_index")
    )

    drop(table(:regents))
  end
end
