defmodule Regents.Repo.Migrations.AddBlogPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:blog_posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:title, :text, null: false)
      add(:description, :text, null: false, default: "")
      add(:date, :date, null: false)
      add(:author, :text, null: false)
      add(:author_x, :text, null: false)
      add(:markdown, :text, null: false)
      add(:draft, :boolean, null: false, default: false)
      add(:cover, :binary, null: false)
      add(:cover_type, :text, null: false)
      add(:cover_alt, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:blog_posts, [:slug], name: "blog_posts_unique_slug_index")
  end

  def down do
    drop_if_exists(unique_index(:blog_posts, [:slug], name: "blog_posts_unique_slug_index"))

    drop(table(:blog_posts))
  end
end
