defmodule AshPlatform.Repo.Migrations.Regent49053FinalC9AutolaunchConsumer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:launch_drafts, prefix: "autolaunch") do
      remove(:recovery_admin)
    end
  end

  def down do
    alter table(:launch_drafts, prefix: "autolaunch") do
      add(:recovery_admin, :text)
    end
  end
end
