defmodule AshPlatform.Repo.Migrations.CreateAutolaunchAuctionsAndTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:tokens, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:symbol, :text, null: false)
      add(:summary, :text)
      add(:graduated_at, :utc_datetime_usec, null: false)
      add(:top_rank, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:auction_id, :uuid, null: false)
    end

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:auctions, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:tokens, prefix: "autolaunch") do
      modify(
        :auction_id,
        references(:auctions, column: :id, name: "tokens_auction_id_fkey", type: :uuid)
      )
    end

    alter table(:auctions, prefix: "autolaunch") do
      add(:title, :text, null: false)
      add(:summary, :text)
      add(:featured, :boolean, null: false, default: false)
      add(:state, :text, null: false, default: "created")
      add(:opened_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:auctions, prefix: "autolaunch") do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:opened_at)
      remove(:state)
      remove(:featured)
      remove(:summary)
      remove(:title)
    end

    drop(constraint(:tokens, "tokens_auction_id_fkey", prefix: "autolaunch"))

    alter table(:tokens, prefix: "autolaunch") do
      modify(:auction_id, :uuid)
    end

    drop(table(:auctions, prefix: "autolaunch"))

    drop(table(:tokens, prefix: "autolaunch"))
  end
end
