defmodule AshPlatform.Repo.Migrations.Regent83952CleanV1BidOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:bid_operations, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action_id, :text, null: false)
      add(:envelope, :map, null: false)
      add(:signer, :text, null: false)
      add(:step, :text, null: false)
      add(:state, :text, null: false, default: "prepared")
      add(:token_approval_transaction_hash, :text)
      add(:permit2_approval_transaction_hash, :text)
      add(:bid_transaction_hash, :text)
      add(:onchain_bid_id, :text)
      add(:reason, :text)
      add(:terminal_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "bid_operations_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ), null: false)
    end

    create unique_index(:bid_operations, [:human_account_id],
             name: "bid_operations_one_open_per_account_index",
             prefix: "autolaunch",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:bid_operations, [:action_id],
             name: "bid_operations_unique_action_id_index",
             prefix: "autolaunch"
           )

    create unique_index(:bid_operations, [:bid_transaction_hash],
             name: "bid_operations_unique_bid_transaction_hash_index",
             prefix: "autolaunch"
           )

    create unique_index(:bid_operations, [:permit2_approval_transaction_hash],
             name: "bid_operations_unique_permit2_approval_transaction_hash_index",
             prefix: "autolaunch"
           )

    create unique_index(:bid_operations, [:token_approval_transaction_hash],
             name: "bid_operations_unique_token_approval_transaction_hash_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop(
      constraint(:bid_operations, "bid_operations_human_account_id_fkey", prefix: "autolaunch")
    )

    drop_if_exists(
      unique_index(:bid_operations, [:token_approval_transaction_hash],
        name: "bid_operations_unique_token_approval_transaction_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:bid_operations, [:permit2_approval_transaction_hash],
        name: "bid_operations_unique_permit2_approval_transaction_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:bid_operations, [:bid_transaction_hash],
        name: "bid_operations_unique_bid_transaction_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:bid_operations, [:action_id],
        name: "bid_operations_unique_action_id_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:bid_operations, [:human_account_id],
        name: "bid_operations_one_open_per_account_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:bid_operations, prefix: "autolaunch"))
  end
end
