defmodule AshPlatform.Repo.Migrations.RegentGu223AccountEnsIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:account_ens_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ens_name, :text)
      add(:ens_avatar_url, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "account_ens_identities_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)
    end

    create unique_index(:account_ens_identities, [:human_account_id],
             name: "account_ens_identities_unique_human_account_index"
           )
  end

  def down do
    drop(constraint(:account_ens_identities, "account_ens_identities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:account_ens_identities, [:human_account_id],
        name: "account_ens_identities_unique_human_account_index"
      )
    )

    drop(table(:account_ens_identities))
  end
end
