defmodule AshPlatform.Repo.Migrations.AddAutolaunchBids do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:bids, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:bid_id, :text, null: false)
      add(:owner_address, :text, null: false)
      add(:amount, :text, null: false)
      add(:max_price, :text)
      add(:current_clearing_price, :text)
      add(:estimated_tokens_if_end_now, :text)
      add(:status, :text, null: false, default: "active")
      add(:exited_at, :utc_datetime_usec)
      add(:claimed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :auction_id,
        references(:auctions,
          column: :id,
          name: "bids_auction_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        ), null: false)
    end

    create index(:bids, [:status], prefix: "autolaunch")

    create index(:bids, [:auction_id], prefix: "autolaunch")

    create index(:bids, [:owner_address], prefix: "autolaunch")

    create unique_index(:bids, [:bid_id], name: "bids_unique_bid_id_index", prefix: "autolaunch")
  end

  def down do
    drop(constraint(:bids, "bids_auction_id_fkey", prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:bids, [:bid_id], name: "bids_unique_bid_id_index", prefix: "autolaunch")
    )

    drop_if_exists(index(:bids, [:owner_address], prefix: "autolaunch"))

    drop_if_exists(index(:bids, [:auction_id], prefix: "autolaunch"))

    drop_if_exists(index(:bids, [:status], prefix: "autolaunch"))

    drop(table(:bids, prefix: "autolaunch"))
  end
end
