defmodule AshPlatform.Repo.Migrations.AddAutolaunchBuybackPreparedActionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tokens, prefix: "autolaunch") do
      add(:price_quote, :text)
      add(:price_source, :text)
      add(:price_updated_at, :utc_datetime_usec)
    end

    alter table(:subjects, prefix: "autolaunch") do
      add(:revenue_router_address, :text)
    end
  end

  def down do
    alter table(:subjects, prefix: "autolaunch") do
      remove(:revenue_router_address)
    end

    alter table(:tokens, prefix: "autolaunch") do
      remove(:price_updated_at)
      remove(:price_source)
      remove(:price_quote)
    end
  end
end
