defmodule Regents.Repo.Migrations.SessionSignedInAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # A sign-in already bound counts from its last refresh, the closest record of it.
  def up do
    alter table(:session_authorities) do
      add(:signed_in_at, :utc_datetime_usec)
    end

    execute("""
    UPDATE regents_app.session_authorities
    SET signed_in_at = updated_at
    WHERE human_account_id IS NOT NULL
    """)
  end

  def down do
    alter table(:session_authorities) do
      remove(:signed_in_at)
    end
  end
end
