defmodule Regents.Repo.Migrations.StakingProtocolReadings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:staking_protocol_readings, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
      add(:history, :map, null: false)
      add(:snapshot, :map, null: false)
      add(:revision, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:staking_protocol_readings))
  end
end
