defmodule Regents.Repo.Migrations.PaperProDailyPapers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:paper_pro_daily_papers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:date, :date, null: false)
      add(:title, :text, null: false)
      add(:arxiv_url, :text, null: false)
      add(:chatgpt_url, :text, null: false)
      add(:author, :text, null: false)
      add(:answer, :text, null: false)
      add(:picture, :binary, null: false)
      add(:picture_type, :text, null: false)
      add(:picture_alt, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:paper_pro_daily_papers, [:date],
             name: "paper_pro_daily_papers_one_a_day_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:paper_pro_daily_papers, [:date],
        name: "paper_pro_daily_papers_one_a_day_index"
      )
    )

    drop(table(:paper_pro_daily_papers))
  end
end
