defmodule AshPlatform.Repo.Migrations.RegentZs64TechtreePublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nodes, prefix: "techtree") do
      add(:kind, :text)
      add(:manifest_digest, :text)
      add(:idempotency_key, :text)
      add(:contributor_id, :text)
      add(:publisher_agent_id, :text)
      add(:publisher_registry_address, :text)
      add(:publisher_token_id, :text)
      add(:publisher_wallet, :text)
      add(:publisher_chain_id, :bigint)
      add(:publisher_regent_id, :uuid)
      add(:siwa_envelope, :map)
    end

    create unique_index(
             :nodes,
             [:publisher_registry_address, :publisher_token_id, :idempotency_key],
             name: "nodes_unique_publisher_idempotency_index",
             prefix: "techtree"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:nodes, [:publisher_registry_address, :publisher_token_id, :idempotency_key],
        name: "nodes_unique_publisher_idempotency_index",
        prefix: "techtree"
      )
    )

    alter table(:nodes, prefix: "techtree") do
      remove(:siwa_envelope)
      remove(:publisher_regent_id)
      remove(:publisher_chain_id)
      remove(:publisher_wallet)
      remove(:publisher_token_id)
      remove(:publisher_registry_address)
      remove(:publisher_agent_id)
      remove(:contributor_id)
      remove(:idempotency_key)
      remove(:manifest_digest)
      remove(:kind)
    end
  end
end
