defmodule AshPlatform.Repo.Migrations.Regent49084AutolaunchIndexerBlockFrontiers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:indexer_blocks, [:chain_id, :finalized, :block_number],
             name: "indexer_blocks_finalized_frontier_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop_if_exists(
      index(:indexer_blocks, [:chain_id, :finalized, :block_number],
        name: "indexer_blocks_finalized_frontier_index",
        prefix: "autolaunch"
      )
    )
  end
end
