defmodule AshPlatform.Repo.Migrations.RemoveTechtree do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(table(:comment_reactions, prefix: "discussions"))

    drop(table(:edges, prefix: "techtree"))

    drop(table(:evidence_state_updates, prefix: "techtree"))

    drop(table(:notebook_artifacts, prefix: "techtree"))

    drop(table(:nodes, prefix: "techtree"))

    drop(table(:trees, prefix: "techtree"))
  end

  def down do
    create table(:trees, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:name, :text, null: false)
      add(:description, :text, null: false)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:trees, [:position],
             name: "trees_unique_position_index",
             prefix: "techtree"
           )

    create unique_index(:trees, [:slug], name: "trees_unique_slug_index", prefix: "techtree")

    create table(:nodes, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:summary, :text)
      add(:payload_hash, :text)
      add(:manifest_cid, :text)
      add(:manifest_hash, :text)
      add(:manifest_uri, :text)
      add(:lineage, :map)
      add(:projection_status, :text, null: false, default: "not_started")
      add(:kind, :text)
      add(:manifest_digest, :text)
      add(:idempotency_key, :text)
      add(:contributor_id, :text)
      add(:publisher_agent_id, :text)
      add(:publisher_registry_address, :text)
      add(:publisher_token_id, :text)
      add(:publisher_wallet, :text)
      add(:publisher_chain_id, :bigint)
      add(:publisher_regent_id, :uuid)
      add(:siwa_envelope, :map)
      add(:pos_x, :float)
      add(:pos_y, :float)
      add(:display_kind, :text, null: false, default: "standard")

      add(:published_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:workflow_state, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :tree_id,
        references(:trees,
          column: :id,
          name: "nodes_tree_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )
    end

    create unique_index(
             :nodes,
             [:publisher_registry_address, :publisher_token_id, :idempotency_key],
             name: "nodes_unique_publisher_idempotency_index",
             prefix: "techtree"
           )

    create index(:nodes, [:tree_id, "published_at DESC", "id ASC"],
             name: "nodes_public_tree_page_index",
             prefix: "techtree"
           )

    create table(:notebook_artifacts, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:node_payload_hash, :text, null: false)
      add(:source_hash, :text, null: false)
      add(:payload_hash, :text, null: false)
      add(:marimo_version, :text, null: false)
      add(:runtime, :text, null: false, default: "pyodide")
      add(:compatibility, :text, null: false, default: "verified")
      add(:run_url, :text, null: false)
      add(:manifest_json, :text, null: false)
      add(:allowed_assets, {:array, :text}, null: false, default: [])

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :node_id,
        references(:nodes,
          column: :id,
          name: "notebook_artifacts_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )
    end

    create unique_index(:notebook_artifacts, [:node_id, :node_payload_hash, :source_hash],
             name: "notebook_artifacts_unique_node_source_index",
             prefix: "techtree"
           )

    create table(:evidence_state_updates, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false)
      add(:reason, :text)
      add(:evidence_reference_ids, {:array, :uuid}, null: false, default: [])
      add(:submitter_agent_id, :text, null: false)
      add(:submitter_registry_address, :text, null: false)
      add(:submitter_token_id, :text, null: false)
      add(:submitter_wallet, :text, null: false)
      add(:submitter_chain_id, :bigint, null: false)
      add(:submitter_regent_id, :uuid, null: false)
      add(:siwa_envelope, :map, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :node_id,
        references(:nodes,
          column: :id,
          name: "evidence_state_updates_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )
    end

    create index(:evidence_state_updates, [:node_id, "inserted_at DESC", "id DESC"],
             name: "evidence_state_updates_node_latest_index",
             prefix: "techtree"
           )

    create table(:edges, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kind, :text, null: false, default: "prerequisite")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :from_node_id,
        references(:nodes,
          column: :id,
          name: "edges_from_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )

      add(
        :to_node_id,
        references(:nodes,
          column: :id,
          name: "edges_to_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )
    end

    create unique_index(:edges, [:from_node_id, :to_node_id],
             name: "edges_unique_pair_index",
             prefix: "techtree"
           )

    create table(:comment_reactions, primary_key: false, prefix: "discussions") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:value, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :comment_id,
        references(:comments,
          column: :id,
          name: "comment_reactions_comment_id_fkey",
          type: :uuid,
          prefix: "discussions"
        ),
        null: false
      )

      add(
        :reactor_id,
        references(:platform_human_users,
          column: :id,
          name: "comment_reactions_reactor_id_fkey",
          type: :bigint,
          prefix: "platform"
        ),
        null: false
      )
    end

    create unique_index(:comment_reactions, [:reactor_id, :comment_id],
             name: "comment_reactions_unique_reactor_comment_index",
             prefix: "discussions"
           )
  end
end
