defmodule AshPlatform.Repo.Migrations.Regent49061CleanV1SubjectWallet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subjects, prefix: "autolaunch") do
      add(:canonical_receiver_address, :text)
    end

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:subject_wallet_operations, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action_id, :text, null: false)
      add(:subject_id, :text, null: false)
      add(:kind, :text, null: false)
      add(:envelope, :map, null: false)
      add(:signer, :text, null: false)
      add(:step, :text, null: false)
      add(:state, :text, null: false, default: "prepared")
      add(:approval_transaction_hash, :text)
      add(:action_transaction_hash, :text)
      add(:result, :map, default: %{})
      add(:reason, :text)
      add(:terminal_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "subject_wallet_operations_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ), null: false)
    end

    create unique_index(:subject_wallet_operations, [:human_account_id, :subject_id],
             name: "subject_wallet_operations_one_open_per_subject_index",
             prefix: "autolaunch",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:subject_wallet_operations, [:action_transaction_hash],
             name: "subject_wallet_operations_unique_action_hash_index",
             prefix: "autolaunch"
           )

    create unique_index(:subject_wallet_operations, [:action_id],
             name: "subject_wallet_operations_unique_action_id_index",
             prefix: "autolaunch"
           )

    create unique_index(:subject_wallet_operations, [:approval_transaction_hash],
             name: "subject_wallet_operations_unique_approval_hash_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop(
      constraint(:subject_wallet_operations, "subject_wallet_operations_human_account_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:subject_wallet_operations, [:approval_transaction_hash],
        name: "subject_wallet_operations_unique_approval_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:subject_wallet_operations, [:action_id],
        name: "subject_wallet_operations_unique_action_id_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:subject_wallet_operations, [:action_transaction_hash],
        name: "subject_wallet_operations_unique_action_hash_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:subject_wallet_operations, [:human_account_id, :subject_id],
        name: "subject_wallet_operations_one_open_per_subject_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:subject_wallet_operations, prefix: "autolaunch"))

    alter table(:subjects, prefix: "autolaunch") do
      remove(:canonical_receiver_address)
    end
  end
end
