defmodule AshPlatform.Repo.Migrations.RegentZs65TechtreeEvidenceStateUpdates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS techtree")

    create table(:evidence_state_updates, primary_key: false, prefix: "techtree") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:status, :text, null: false)
      add(:reason, :text)
      add(:evidence_reference_ids, {:array, :uuid}, null: false, default: [])
      add(:submitter_agent_id, :text, null: false)
      add(:submitter_registry_address, :text, null: false)
      add(:submitter_token_id, :text, null: false)
      add(:submitter_wallet, :text, null: false)
      add(:submitter_chain_id, :bigint, null: false)
      add(:submitter_regent_id, :uuid, null: false)
      add(:siwa_envelope, :map, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :node_id,
        references(:nodes,
          column: :id,
          name: "evidence_state_updates_node_id_fkey",
          type: :uuid,
          prefix: "techtree"
        ),
        null: false
      )
    end

    create index(:evidence_state_updates, [:node_id, "inserted_at DESC", "id DESC"],
             name: "evidence_state_updates_node_latest_index",
             prefix: "techtree"
           )
  end

  def down do
    drop(
      constraint(:evidence_state_updates, "evidence_state_updates_node_id_fkey",
        prefix: "techtree"
      )
    )

    drop_if_exists(
      index(:evidence_state_updates, [:node_id, "inserted_at DESC", "id DESC"],
        name: "evidence_state_updates_node_latest_index",
        prefix: "techtree"
      )
    )

    drop(table(:evidence_state_updates, prefix: "techtree"))
  end
end
