defmodule AshPlatform.Repo.Migrations.RegentZs64FailSafeWorkflowState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nodes, prefix: "techtree") do
      modify(:workflow_state, :text, default: nil)
    end
  end

  def down do
    alter table(:nodes, prefix: "techtree") do
      modify(:workflow_state, :text, default: "published")
    end
  end
end
