defmodule AshPlatform.Repo.Migrations.Regent49081AutolaunchChainLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:indexer_sources, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:chain_id, :bigint, null: false)
      add(:address, :text, null: false)
      add(:start_block, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:indexer_sources, [:chain_id, :address],
             name: "indexer_sources_unique_source_index",
             prefix: "autolaunch"
           )

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:indexer_logs, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:chain_id, :bigint, null: false)
      add(:block_hash, :text, null: false)
      add(:log_index, :bigint, null: false)
      add(:transaction_hash, :text, null: false)
      add(:transaction_index, :bigint, null: false)
      add(:address, :text, null: false)
      add(:topics, {:array, :text}, null: false)
      add(:data, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:block_id, :uuid, null: false)
    end

    create unique_index(:indexer_logs, [:chain_id, :block_hash, :log_index],
             name: "indexer_logs_unique_log_index",
             prefix: "autolaunch"
           )

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:indexer_cursors, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:chain_id, :bigint, null: false)
      add(:next_block_to_fetch, :bigint, null: false)
      add(:lease_owner, :text)
      add(:lease_expires_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:indexer_cursors, [:chain_id],
             name: "indexer_cursors_unique_chain_index",
             prefix: "autolaunch"
           )

    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:indexer_blocks, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:indexer_logs, prefix: "autolaunch") do
      modify(
        :block_id,
        references(:indexer_blocks,
          column: :id,
          name: "indexer_logs_block_id_fkey",
          type: :uuid,
          on_delete: :restrict
        )
      )
    end

    alter table(:indexer_blocks, prefix: "autolaunch") do
      add(:chain_id, :bigint, null: false)
      add(:block_number, :bigint, null: false)
      add(:block_hash, :text, null: false)
      add(:parent_hash, :text, null: false)
      add(:canonical, :boolean, null: false, default: true)
      add(:finalized, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:indexer_blocks, [:chain_id, :block_number], prefix: "autolaunch")

    create unique_index(:indexer_blocks, [:chain_id, :block_hash],
             name: "indexer_blocks_unique_block_index",
             prefix: "autolaunch"
           )

    create constraint(:indexer_blocks, :indexer_blocks_block_number_nonnegative,
             check: """
               block_number >= 0
             """,
             prefix: "autolaunch"
           )

    create constraint(:indexer_cursors, :indexer_cursors_next_block_nonnegative,
             check: """
               next_block_to_fetch >= 0
             """,
             prefix: "autolaunch"
           )

    create constraint(:indexer_logs, :indexer_logs_log_index_nonnegative,
             check: """
               log_index >= 0
             """,
             prefix: "autolaunch"
           )

    create constraint(:indexer_logs, :indexer_logs_transaction_index_nonnegative,
             check: """
               transaction_index >= 0
             """,
             prefix: "autolaunch"
           )

    create constraint(:indexer_sources, :indexer_sources_start_block_nonnegative,
             check: """
               start_block >= 0
             """,
             prefix: "autolaunch"
           )
  end

  def down do
    drop_if_exists(
      constraint(:indexer_sources, :indexer_sources_start_block_nonnegative, prefix: "autolaunch")
    )

    drop_if_exists(
      constraint(:indexer_logs, :indexer_logs_transaction_index_nonnegative, prefix: "autolaunch")
    )

    drop_if_exists(
      constraint(:indexer_logs, :indexer_logs_log_index_nonnegative, prefix: "autolaunch")
    )

    drop_if_exists(
      constraint(:indexer_cursors, :indexer_cursors_next_block_nonnegative, prefix: "autolaunch")
    )

    drop_if_exists(
      constraint(:indexer_blocks, :indexer_blocks_block_number_nonnegative, prefix: "autolaunch")
    )

    drop_if_exists(
      unique_index(:indexer_blocks, [:chain_id, :block_hash],
        name: "indexer_blocks_unique_block_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(index(:indexer_blocks, [:chain_id, :block_number], prefix: "autolaunch"))

    alter table(:indexer_blocks, prefix: "autolaunch") do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:finalized)
      remove(:canonical)
      remove(:parent_hash)
      remove(:block_hash)
      remove(:block_number)
      remove(:chain_id)
    end

    drop(constraint(:indexer_logs, "indexer_logs_block_id_fkey", prefix: "autolaunch"))

    alter table(:indexer_logs, prefix: "autolaunch") do
      modify(:block_id, :uuid)
    end

    drop(table(:indexer_blocks, prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:indexer_cursors, [:chain_id],
        name: "indexer_cursors_unique_chain_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:indexer_cursors, prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:indexer_logs, [:chain_id, :block_hash, :log_index],
        name: "indexer_logs_unique_log_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:indexer_logs, prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:indexer_sources, [:chain_id, :address],
        name: "indexer_sources_unique_source_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:indexer_sources, prefix: "autolaunch"))
  end
end
