defmodule AshPlatform.Repo.Migrations.Regent49058AccountOwnedLaunchDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:launch_draft_images, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:digest, :text, null: false)
      add(:content_type, :text, null: false)
      add(:byte_size, :bigint, null: false)
      add(:bytes, :binary, null: false)
      add(:original_filename, :text, null: false)

      add(
        :launch_draft_id,
        references(:launch_drafts,
          column: :id,
          name: "launch_draft_images_launch_draft_id_fkey",
          type: :uuid,
          prefix: "autolaunch",
          on_delete: :restrict
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "launch_draft_images_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create unique_index(:launch_draft_images, [:human_account_id],
             name: "launch_draft_images_one_image_per_owner_index",
             prefix: "autolaunch"
           )

    create index(:launch_draft_images, [:launch_draft_id], prefix: "autolaunch")

    create unique_index(:launch_draft_images, [:id, :launch_draft_id, :human_account_id],
             name: "launch_draft_images_exact_provenance_index",
             prefix: "autolaunch"
           )

    create constraint(:launch_draft_images, :launch_draft_images_derived_size,
             prefix: "autolaunch",
             check: "byte_size = octet_length(bytes) AND byte_size BETWEEN 1 AND 2097152"
           )

    create constraint(:launch_draft_images, :launch_draft_images_content_type,
             prefix: "autolaunch",
             check: "content_type IN ('image/png', 'image/jpeg', 'image/webp')"
           )

    create constraint(:launch_draft_images, :launch_draft_images_digest,
             prefix: "autolaunch",
             check: "digest ~ '^[0-9a-f]{64}$'"
           )

    create constraint(:launch_draft_images, :launch_draft_images_filename,
             prefix: "autolaunch",
             check: "octet_length(original_filename) BETWEEN 1 AND 255"
           )

    alter table(:launch_drafts, prefix: "autolaunch") do
      modify(:token_name, :text, null: false, default: "")
      modify(:symbol, :text, null: false, default: "")
      modify(:regent_id, :uuid, null: true)
      add(:eoa_acknowledgement, :text)
      add(:launch_draft_image_id, :uuid)
    end

    create index(:launch_drafts, [:launch_draft_image_id], prefix: "autolaunch")

    create unique_index(:launch_drafts, [:id, :human_account_id],
             name: "launch_drafts_exact_owner_index",
             prefix: "autolaunch"
           )

    execute("""
    ALTER TABLE autolaunch.launch_draft_images
    ADD CONSTRAINT launch_draft_images_exact_owner_fkey
    FOREIGN KEY (launch_draft_id, human_account_id)
    REFERENCES autolaunch.launch_drafts (id, human_account_id)
    ON DELETE RESTRICT
    """)

    execute("""
    ALTER TABLE autolaunch.launch_drafts
    ADD CONSTRAINT launch_drafts_exact_image_fkey
    FOREIGN KEY (launch_draft_image_id, id, human_account_id)
    REFERENCES autolaunch.launch_draft_images (id, launch_draft_id, human_account_id)
    ON DELETE RESTRICT
    """)
  end

  def down do
    # A downgrade has no truthful way to restore a Regent relationship for a
    # Human-owned draft or to preserve an immutable image after dropping its
    # table. Refuse before changing anything instead of inventing provenance or
    # deleting customer data.
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM autolaunch.launch_drafts
        WHERE regent_id IS NULL
           OR eoa_acknowledgement IS NOT NULL
           OR launch_draft_image_id IS NOT NULL
      ) OR EXISTS (
        SELECT 1 FROM autolaunch.launch_draft_images
      ) THEN
        RAISE EXCEPTION 'cannot downgrade account-owned launch drafts without losing provenance or immutable image data';
      END IF;
    END
    $$;
    """)

    execute("ALTER TABLE autolaunch.launch_drafts DROP CONSTRAINT launch_drafts_exact_image_fkey")

    execute(
      "ALTER TABLE autolaunch.launch_draft_images DROP CONSTRAINT launch_draft_images_exact_owner_fkey"
    )

    drop_if_exists(index(:launch_drafts, [:launch_draft_image_id], prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:launch_drafts, [:id, :human_account_id],
        name: "launch_drafts_exact_owner_index",
        prefix: "autolaunch"
      )
    )

    alter table(:launch_drafts, prefix: "autolaunch") do
      remove(:launch_draft_image_id)
      remove(:eoa_acknowledgement)
      modify(:regent_id, :uuid, null: false)
      modify(:symbol, :text, null: false, default: nil)
      modify(:token_name, :text, null: false, default: nil)
    end

    drop(
      constraint(:launch_draft_images, "launch_draft_images_human_account_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop(
      constraint(:launch_draft_images, "launch_draft_images_launch_draft_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_draft_images, [:human_account_id],
        name: "launch_draft_images_one_image_per_owner_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_draft_images, [:id, :launch_draft_id, :human_account_id],
        name: "launch_draft_images_exact_provenance_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(index(:launch_draft_images, [:launch_draft_id], prefix: "autolaunch"))

    drop(table(:launch_draft_images, prefix: "autolaunch"))
  end
end
