defmodule AshPlatform.Repo.Migrations.CreateRegents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:regents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:display_name, :text, null: false)
      add(:summary, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "regents_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ),
        null: false
      )
    end

    create unique_index(:regents, [:human_account_id], name: "regents_unique_human_account_index")

    create unique_index(:regents, [:slug], name: "regents_unique_slug_index")
  end

  def down do
    drop(constraint(:regents, "regents_human_account_id_fkey"))

    drop_if_exists(unique_index(:regents, [:slug], name: "regents_unique_slug_index"))

    drop_if_exists(
      unique_index(:regents, [:human_account_id], name: "regents_unique_human_account_index")
    )

    drop(table(:regents))
  end
end
