defmodule AshPlatform.Repo.Migrations.Regent6eb12SessionAuthorities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:session_authorities, primary_key: false) do
      add(:lineage, :uuid, null: false, primary_key: true)
      add(:generation, :bigint, null: false, default: 0)
      add(:revoked_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "session_authorities_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict,
          on_update: :restrict
        )
      )
    end

    create constraint(:session_authorities, :session_authorities_generation_non_negative,
             check: """
               generation >= 0
             """
           )

    create constraint(:session_authorities, :session_authorities_terminal_revocation,
             check: """
               (revoked_at IS NULL AND human_account_id IS NOT NULL AND generation < 9223372036854775807) OR (revoked_at IS NOT NULL AND generation = 9223372036854775807)
             """
           )
  end

  def down do
    drop_if_exists(constraint(:session_authorities, :session_authorities_terminal_revocation))

    drop_if_exists(constraint(:session_authorities, :session_authorities_generation_non_negative))

    drop(constraint(:session_authorities, "session_authorities_human_account_id_fkey"))

    drop(table(:session_authorities))
  end
end
