defmodule AshPlatform.Repo.Migrations.Regent83911StakeRedeemOperations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stake_redeem_operations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:action_id, :text, null: false)
      add(:capability, :text, null: false)
      add(:action, :text, null: false)
      add(:envelope, :map, null: false)
      add(:state, :text, null: false, default: "prepared")
      add(:approval_dispatched_at, :utc_datetime_usec)
      add(:approval_transaction_hash, :text)
      add(:approval_receipt_at, :utc_datetime_usec)
      add(:approval_reread_at, :utc_datetime_usec)
      add(:action_dispatched_at, :utc_datetime_usec)
      add(:action_transaction_hash, :text)
      add(:action_receipt_at, :utc_datetime_usec)
      add(:action_reread_at, :utc_datetime_usec)
      add(:reason, :text)
      add(:terminal_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "stake_redeem_operations_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ), null: false)
    end

    create unique_index(:stake_redeem_operations, [:human_account_id, :capability],
             name: "stake_redeem_operations_one_active_per_capability_index",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:stake_redeem_operations, [:action_id],
             name: "stake_redeem_operations_unique_action_id_index"
           )

    create unique_index(:stake_redeem_operations, [:action_transaction_hash],
             name: "stake_redeem_operations_unique_action_transaction_hash_index"
           )

    create unique_index(:stake_redeem_operations, [:approval_transaction_hash],
             name: "stake_redeem_operations_unique_approval_transaction_hash_index"
           )
  end

  def down do
    drop(constraint(:stake_redeem_operations, "stake_redeem_operations_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:stake_redeem_operations, [:approval_transaction_hash],
        name: "stake_redeem_operations_unique_approval_transaction_hash_index"
      )
    )

    drop_if_exists(
      unique_index(:stake_redeem_operations, [:action_transaction_hash],
        name: "stake_redeem_operations_unique_action_transaction_hash_index"
      )
    )

    drop_if_exists(
      unique_index(:stake_redeem_operations, [:action_id],
        name: "stake_redeem_operations_unique_action_id_index"
      )
    )

    drop_if_exists(
      unique_index(:stake_redeem_operations, [:human_account_id, :capability],
        name: "stake_redeem_operations_one_active_per_capability_index"
      )
    )

    drop(table(:stake_redeem_operations))
  end
end
