defmodule AshPlatform.Repo.Migrations.AddAutolaunchLaunchJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:launch_jobs, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:job_id, :text, null: false)
      add(:status, :text, null: false)
      add(:step, :text, null: false)
      add(:agent_id, :text, null: false)
      add(:agent_name, :text)
      add(:token_name, :text, null: false)
      add(:token_symbol, :text, null: false)
      add(:chain_id, :bigint, null: false)
      add(:agent_safe_address, :text)
      add(:auction_address, :text)
      add(:token_address, :text)
      add(:hook_address, :text)
      add(:revenue_share_splitter_address, :text)
      add(:started_at, :utc_datetime_usec)
      add(:finished_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :auction_id,
        references(:auctions,
          column: :id,
          name: "launch_jobs_auction_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end

    create unique_index(:launch_jobs, [:job_id],
             name: "launch_jobs_unique_job_id_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop(constraint(:launch_jobs, "launch_jobs_auction_id_fkey", prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:launch_jobs, [:job_id],
        name: "launch_jobs_unique_job_id_index",
        prefix: "autolaunch"
      )
    )

    drop(table(:launch_jobs, prefix: "autolaunch"))
  end
end
