defmodule AshPlatform.Repo.Migrations.AgentPairing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:agent_pairing_codes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code_hash, :text, null: false)
      add(:issued_at, :utc_datetime_usec, null: false)
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "agent_pairing_codes_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)

      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "agent_pairing_codes_regent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:agent_pairing_codes, [:regent_id])

    create unique_index(:agent_pairing_codes, [:code_hash],
             name: "agent_pairing_codes_unique_code_hash_index"
           )

    create unique_index(:agent_pairing_codes, [:human_account_id],
             name: "agent_pairing_codes_unique_human_account_index"
           )

    create table(:agent_links, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:agent_id, :text, null: false)
      add(:registry_address, :text, null: false)
      add(:token_id, :text, null: false)
      add(:wallet, :text, null: false)
      add(:paired_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "agent_links_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)

      add(
        :regent_id,
        references(:regents,
          column: :id,
          name: "agent_links_regent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create index(:agent_links, [:regent_id])

    create index(:agent_links, [:human_account_id])

    create unique_index(:agent_links, [:agent_id], name: "agent_links_unique_agent_id_index")

    create unique_index(:agent_links, [:registry_address, :token_id],
             name: "agent_links_unique_registry_token_index"
           )
  end

  def down do
    drop(constraint(:agent_links, "agent_links_human_account_id_fkey"))

    drop(constraint(:agent_links, "agent_links_regent_id_fkey"))

    drop_if_exists(
      unique_index(:agent_links, [:registry_address, :token_id],
        name: "agent_links_unique_registry_token_index"
      )
    )

    drop_if_exists(
      unique_index(:agent_links, [:agent_id], name: "agent_links_unique_agent_id_index")
    )

    drop_if_exists(index(:agent_links, [:human_account_id]))

    drop_if_exists(index(:agent_links, [:regent_id]))

    drop(table(:agent_links))

    drop(constraint(:agent_pairing_codes, "agent_pairing_codes_human_account_id_fkey"))

    drop(constraint(:agent_pairing_codes, "agent_pairing_codes_regent_id_fkey"))

    drop_if_exists(
      unique_index(:agent_pairing_codes, [:human_account_id],
        name: "agent_pairing_codes_unique_human_account_index"
      )
    )

    drop_if_exists(
      unique_index(:agent_pairing_codes, [:code_hash],
        name: "agent_pairing_codes_unique_code_hash_index"
      )
    )

    drop_if_exists(index(:agent_pairing_codes, [:regent_id]))

    drop(table(:agent_pairing_codes))
  end
end
