defmodule AshPlatform.Repo.Migrations.Regent49051CleanV1LaunchDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:launch_drafts, prefix: "autolaunch") do
      modify(:title, :text, null: true)
      add(:website, :text)
      add(:image, :text)
      add(:treasury, :text)
      add(:recovery_admin, :text)
      add(:required_regent_raised, :text)
    end
  end

  def down do
    # Clean V1 writes no title, so restoring the old NOT NULL rule would fail on
    # every row written since. Each such row gets the name it already holds, and
    # no row and no column is taken away.
    execute(~s(UPDATE "autolaunch"."launch_drafts" SET "title" = "token_name" WHERE "title" IS NULL))

    alter table(:launch_drafts, prefix: "autolaunch") do
      remove(:required_regent_raised)
      remove(:recovery_admin)
      remove(:treasury)
      remove(:image)
      remove(:website)
      modify(:title, :text, null: false)
    end
  end
end
