defmodule AshPlatform.Repo.Migrations.Regent49059AutolaunchLaunchpadRedesign do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions, prefix: "autolaunch") do
      add(:token_symbol, :text)
      add(:website, :text)
      add(:image, :text)

      add(
        :creator_human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "auctions_creator_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        )
      )
    end

    create table(:x_connections, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text, null: false)
      add(:x_user_id, :text)
      add(:username, :text)
      add(:display_name, :text)
      add(:avatar_url, :text)
      add(:verified_at, :utc_datetime_usec)
      add(:attempt_state, :text)
      add(:attempt_verifier, :text)
      add(:attempt_generation, :uuid)
      add(:attempt_expires_at, :utc_datetime_usec)
      add(:intent_sequence, :bigint)
      add(:intent_generation, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "x_connections_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :delete_all
        ), null: false)
    end

    create unique_index(:x_connections, [:human_account_id, :role],
             name: "x_connections_one_role_per_human_index"
           )
  end

  def down do
    drop(constraint(:x_connections, "x_connections_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:x_connections, [:human_account_id, :role],
        name: "x_connections_one_role_per_human_index"
      )
    )

    drop(table(:x_connections))

    drop(constraint(:auctions, "auctions_creator_human_account_id_fkey", prefix: "autolaunch"))

    alter table(:auctions, prefix: "autolaunch") do
      remove(:creator_human_account_id)
      remove(:image)
      remove(:website)
      remove(:token_symbol)
    end
  end
end
