defmodule AshPlatform.Repo.Migrations.Regent49055VerifiedTreasuryCustody do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:treasury_security_reports, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:address, :text, null: false)
      add(:chain_id, :bigint, null: false)
      add(:classification, :text, null: false)
      add(:safe_version, :text)
      add(:safe_singleton, :text)
      add(:owner_addresses, {:array, :text}, null: false, default: [])
      add(:owner_count, :bigint, null: false, default: 0)
      add(:threshold, :bigint)
      add(:modules, {:array, :text}, null: false, default: [])
      add(:guard, :text)
      add(:fallback_handler, :text)
      add(:configuration_fingerprint, :text, null: false)
      add(:source_block_number, :bigint, null: false)
      add(:source_block_hash, :text, null: false)
      add(:observed_at, :utc_datetime_usec, null: false)
      add(:verification_state, :text, null: false)
      add(:verification_reason, :text, null: false)
      add(:usdc_evidence, :map)
      add(:regent_evidence, :map)
      add(:outbound_evidence, :map)
      add(:downgrade_state, :text, null: false, default: "none")
      add(:prior_verified_fingerprint, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create index(:treasury_security_reports, [:address, :source_block_number],
             prefix: "autolaunch"
           )

    alter table(:tokens, prefix: "autolaunch") do
      add(
        :treasury_security_report_id,
        references(:treasury_security_reports,
          column: :id,
          name: "tokens_treasury_security_report_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end

    alter table(:subjects, prefix: "autolaunch") do
      add(
        :treasury_security_report_id,
        references(:treasury_security_reports,
          column: :id,
          name: "subjects_treasury_security_report_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end

    alter table(:launch_jobs, prefix: "autolaunch") do
      add(
        :treasury_security_report_id,
        references(:treasury_security_reports,
          column: :id,
          name: "launch_jobs_treasury_security_report_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end

    alter table(:launch_drafts, prefix: "autolaunch") do
      add(:treasury_path, :text, null: false, default: "safe")
    end

    alter table(:auctions, prefix: "autolaunch") do
      add(
        :treasury_security_report_id,
        references(:treasury_security_reports,
          column: :id,
          name: "auctions_treasury_security_report_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end
  end

  def down do
    drop(constraint(:auctions, "auctions_treasury_security_report_id_fkey", prefix: "autolaunch"))

    alter table(:auctions, prefix: "autolaunch") do
      remove(:treasury_security_report_id)
    end

    alter table(:launch_drafts, prefix: "autolaunch") do
      remove(:treasury_path)
    end

    drop(
      constraint(:launch_jobs, "launch_jobs_treasury_security_report_id_fkey",
        prefix: "autolaunch"
      )
    )

    alter table(:launch_jobs, prefix: "autolaunch") do
      remove(:treasury_security_report_id)
    end

    drop(constraint(:subjects, "subjects_treasury_security_report_id_fkey", prefix: "autolaunch"))

    alter table(:subjects, prefix: "autolaunch") do
      remove(:treasury_security_report_id)
    end

    drop(constraint(:tokens, "tokens_treasury_security_report_id_fkey", prefix: "autolaunch"))

    alter table(:tokens, prefix: "autolaunch") do
      remove(:treasury_security_report_id)
    end

    drop_if_exists(
      index(:treasury_security_reports, [:address, :source_block_number], prefix: "autolaunch")
    )

    drop(table(:treasury_security_reports, prefix: "autolaunch"))
  end
end
