defmodule AshPlatform.Repo.Migrations.AddLinkedIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:linked_identities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:provider, :text, null: false)
      add(:subject, :text, null: false)
      add(:username, :text)
      add(:display_name, :text)
      add(:verified_at, :utc_datetime_usec, null: false)
      add(:metadata, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "linked_identities_human_account_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)
    end

    create unique_index(:linked_identities, [:provider, :human_account_id],
             name: "linked_identities_unique_provider_per_account_index"
           )

    create unique_index(:linked_identities, [:provider, :subject],
             name: "linked_identities_unique_subject_per_provider_index"
           )
  end

  def down do
    drop(constraint(:linked_identities, "linked_identities_human_account_id_fkey"))

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :subject],
        name: "linked_identities_unique_subject_per_provider_index"
      )
    )

    drop_if_exists(
      unique_index(:linked_identities, [:provider, :human_account_id],
        name: "linked_identities_unique_provider_per_account_index"
      )
    )

    drop(table(:linked_identities))
  end
end
