defmodule AshPlatform.Repo.Migrations.Regent49058AccountOwnedLaunchDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:launch_draft_images, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:digest, :text, null: false)
      add(:content_type, :text, null: false)
      add(:byte_size, :bigint, null: false)
      add(:bytes, :binary, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :human_account_id,
        references(:platform_human_users,
          column: :id,
          name: "launch_draft_images_human_account_id_fkey",
          type: :bigint,
          prefix: "platform",
          on_delete: :restrict
        ), null: false)
    end

    create index(:launch_draft_images, [:human_account_id], prefix: "autolaunch")

    create unique_index(:launch_draft_images, [:human_account_id, :digest],
             name: "launch_draft_images_unique_owner_digest_index",
             prefix: "autolaunch"
           )

    alter table(:launch_drafts, prefix: "autolaunch") do
      modify(:regent_id, :uuid, null: true)
      modify(:symbol, :text, null: true)
      modify(:token_name, :text, null: true)
      add(:eoa_acknowledgement, :text)

      add(
        :launch_draft_image_id,
        references(:launch_draft_images,
          column: :id,
          name: "launch_drafts_launch_draft_image_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        )
      )
    end

    create index(:launch_drafts, [:launch_draft_image_id], prefix: "autolaunch")
  end

  def down do
    # A downgrade has no truthful way to restore a Regent relationship for a
    # Human-owned draft or to preserve an immutable image after dropping its
    # table. Refuse before changing anything instead of inventing provenance or
    # deleting customer data.
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM autolaunch.launch_drafts
        WHERE regent_id IS NULL
           OR token_name IS NULL
           OR symbol IS NULL
           OR eoa_acknowledgement IS NOT NULL
           OR launch_draft_image_id IS NOT NULL
      ) OR EXISTS (
        SELECT 1 FROM autolaunch.launch_draft_images
      ) THEN
        RAISE EXCEPTION 'cannot downgrade account-owned launch drafts without losing provenance or immutable image data';
      END IF;
    END
    $$;
    """)

    drop(
      constraint(:launch_drafts, "launch_drafts_launch_draft_image_id_fkey", prefix: "autolaunch")
    )

    drop_if_exists(index(:launch_drafts, [:launch_draft_image_id], prefix: "autolaunch"))

    alter table(:launch_drafts, prefix: "autolaunch") do
      remove(:launch_draft_image_id)
      remove(:eoa_acknowledgement)
      modify(:token_name, :text, null: false)
      modify(:symbol, :text, null: false)
      modify(:regent_id, :uuid, null: false)
    end

    drop(
      constraint(:launch_draft_images, "launch_draft_images_human_account_id_fkey",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(
      unique_index(:launch_draft_images, [:human_account_id, :digest],
        name: "launch_draft_images_unique_owner_digest_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(index(:launch_draft_images, [:human_account_id], prefix: "autolaunch"))

    drop(table(:launch_draft_images, prefix: "autolaunch"))
  end
end
