defmodule AshPlatform.Repo.Migrations.AddUniqueAutolaunchTokenAuction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:tokens, [:auction_id],
             name: "tokens_unique_auction_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:tokens, [:auction_id],
        name: "tokens_unique_auction_index",
        prefix: "autolaunch"
      )
    )
  end
end
