defmodule AshPlatform.Repo.Migrations.AddAutolaunchPaymentLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS autolaunch")

    create table(:payment_links, primary_key: false, prefix: "autolaunch") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:receiver_address, :text, null: false)
      add(:label, :text, null: false)

      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :subject_id,
        references(:subjects,
          column: :id,
          name: "payment_links_subject_id_fkey",
          type: :uuid,
          prefix: "autolaunch"
        ), null: false)
    end

    create index(:payment_links, [:subject_id], prefix: "autolaunch")

    create unique_index(:payment_links, [:receiver_address],
             name: "payment_links_unique_receiver_address_index",
             prefix: "autolaunch"
           )
  end

  def down do
    drop(constraint(:payment_links, "payment_links_subject_id_fkey", prefix: "autolaunch"))

    drop_if_exists(
      unique_index(:payment_links, [:receiver_address],
        name: "payment_links_unique_receiver_address_index",
        prefix: "autolaunch"
      )
    )

    drop_if_exists(index(:payment_links, [:subject_id], prefix: "autolaunch"))

    drop(table(:payment_links, prefix: "autolaunch"))
  end
end
