defmodule AshPlatform.Repo.Migrations.CreateRecordComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS discussions")

    create table(:comments, primary_key: false, prefix: "discussions") do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:target_type, :text, null: false)
      add(:target_id, :uuid, null: false)
      add(:body, :text, null: false)
      add(:client_request_id, :uuid, null: false)
      add(:deleted_at, :utc_datetime_usec)
      add(:deleted_by_human_account_id, :bigint)
      add(:deletion_authority, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :author_id,
        references(:platform_human_users,
          column: :id,
          name: "comments_author_id_fkey",
          type: :bigint,
          prefix: "platform"
        ), null: false)
    end

    create unique_index(:comments, [:author_id, :client_request_id],
             name: "comments_unique_author_request_index",
             prefix: "discussions"
           )
  end

  def down do
    drop(constraint(:comments, "comments_author_id_fkey", prefix: "discussions"))

    drop_if_exists(
      unique_index(:comments, [:author_id, :client_request_id],
        name: "comments_unique_author_request_index",
        prefix: "discussions"
      )
    )

    drop(table(:comments, prefix: "discussions"))
  end
end
