defmodule AshPlatform.Repo.Migrations.Regent49081CanonicalHeightAndFinality do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(index(:indexer_blocks, [:chain_id, :block_number], prefix: "autolaunch"))

    create index(:indexer_blocks, [:chain_id, :block_number],
             name: "indexer_blocks_canonical_height_index",
             unique: true,
             where: "canonical",
             prefix: "autolaunch"
           )

    create constraint(:indexer_blocks, :indexer_blocks_finalized_is_canonical,
             check: """
               canonical or not finalized
             """,
             prefix: "autolaunch"
           )
  end

  def down do
    drop_if_exists(
      constraint(:indexer_blocks, :indexer_blocks_finalized_is_canonical, prefix: "autolaunch")
    )

    drop_if_exists(
      index(:indexer_blocks, [:chain_id, :block_number],
        name: "indexer_blocks_canonical_height_index",
        prefix: "autolaunch"
      )
    )

    create index(:indexer_blocks, [:chain_id, :block_number], prefix: "autolaunch")
  end
end
